2025-06-05 17:21:08,992 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 725716b6df2a2ce3060b1681ae49712313e3156ab2af1b2ee7585b72b69dc7d5
2025-06-05 17:21:09,002 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 92a824aec75ad8302e5f546fd2531c8ff87762bfd72e5050b6120a69c4a99baa
2025-06-05 17:21:09,003 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 7f80d821a920baa16aca54f9d2816af25ef763dac0e91a14b00abc0f87419976
2025-06-05 17:21:09,032 - ERROR - Exception occurred in 62d9b02a491b778cf53dabbd22c6ef5b691db9126261ac878e2c236f26213622: 4ca1800417ef883aa00703957a628d7ad46ba2f155fb19c8dde52e28011a866e
2025-06-05 17:21:09,033 - ERROR - Traceback (most recent call last):
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 76, in add_user
    cursor.execute(query, (Fname, Lname, Uname, Pword, Role, Rdate))
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

2025-06-05 17:21:19,056 - INFO - [48db9125ac8b4c70f6eccdd2496afa6540b8f72c689a59c6c9fe2ceee405a5d1] 45ce626be5b1c6079dd57fbf67048dde423852cadbf7a9d8ba397af4f8aafa2d
2025-06-05 17:21:19,056 - INFO - [48db9125ac8b4c70f6eccdd2496afa6540b8f72c689a59c6c9fe2ceee405a5d1] 82eb18222c5b2b98dc852ff19378c126d9ddc43a7e70743b7368ec3d926728fe
