2025-06-16 18:02:09,665 - INFO - User activity logged: Super Admin, Logged in, , Low Risk
2025-06-16 18:02:09,672 - INFO - User activity logged: super_admin, Accessed Super Administrator Dashboard, , Low Risk
2025-06-16 18:02:15,038 - ERROR - User activity logged: super_admin, An unexpected error occurred in the Super Administrator Dashboard, Traceback (most recent call last):
  File "C:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\user_interface.py", line 84, in landing_super_admin
    self.data_management_super_admin(user)
  File "C:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\user_interface.py", line 329, in data_management_super_admin
    if user.view_logs(self._db, self._logger):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\models.py", line 1008, in view_logs
    print(f"ID: {Helper.symmetric_decrypt(log[0])}, "
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\helper.py", line 88, in symmetric_decrypt
    return engine.decrypt(encrypted).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cryptography\fernet.py", line 111, in _get_unverified_token_data
    raise TypeError("token must be bytes or str")
TypeError: token must be bytes or str
, High Risk
